[workspace]
members = [
	".",
	"codegen",
	"example",
]

[package]
name = "willow"
version = "0.1.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"

[dependencies]
cfg-if = "1.0.0"
paste = "1.0.5"
typed-builder = "0.9.0"

[dependencies.nalgebra]
version = "0.26.2"
optional = true

[dependencies.willow-codegen]
version = "0.1.0"
path = "codegen"

[dependencies.web-sys]
version = "0.3.47"
features = [
	"WebGlBuffer",
	"WebGlProgram",
	"WebGlRenderingContext",
	"WebGlShader",
	"WebGlUniformLocation",
]

[features]
default = ["nalgebra"]
