[package]
name = "willow-codegen"
version = "0.1.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
heck = "0.3.2"
proc-macro2 = "1.0.24"
quote = "1.0.9"

[dependencies.syn]
version = "1.0.60"
features = ["full"]
